spring.application.name=Gachimeokja

# spring.datasource.url=jdbc:mysql://database-1.cj6yocgc61n5.ap-northeast-2.rds.amazonaws.com:3306/gachimeokja
# spring.datasource.username=admin
# spring.datasource.password=!Dongguk12345
# 테스트용 로컬 db
spring.datasource.url=jdbc:mysql://localhost:3306/local_db
spring.datasource.username=root
spring.datasource.password=nomyek341!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Connection Pool 설정
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10